### PR TITLE
Feature/abilities

### PR DESCRIPTION
**Pull request by recca20**
spells, mana regen when not casting, cooldown between spell cast, damagetaken.
https://trello.com/c/FPY1iU4r/49-as-a-player-i-want-to-use-magic-abilities-to-deal-damage-to-enemy

How to use:
there is a comment where to attach the code.
obs dont forget the enemy tag.

### CODE REVIEW

**Review by FelixAtForsberg — CHANGES_REQUESTED** [review]
1. Please conform to the project folder structure, as outlined in the [technical document](https://docs.google.com/document/d/1G1FRt30GkujD9pizI5bsZ7yJgD05wlP7GjoBy02OS_c/edit#heading=h.kuwlueacq1hm)

Scripts would go under `Scripts/Abilities/`
Scriptable objects would go under `ScriptableObjects/Abilities/`
etc

1. Remove the scene from the commit, unless it is required. If required, please rename it to avoid merge conflicts. 

1. Remove the conflict inducing "Packages" folder, note to self: I need to ask Marc how he thinks we should handle package dependencies.

**Comment by recca20** [comment]
organized project folder structure
removed scene that not needed
removed packages

**Review by FelixAtForsberg — CHANGES_REQUESTED** [review]
All of your work is supposed to go somewhere under the `assets/` folder.

While it may be slightly more work, we're not structuring by feature but by asset type. Having a lot of "abilities" folders under their correct asset type is not a bad thing.

If you don't quite understand how or why, I suggest we do some pair programming.

**Review by FelixAtForsberg — CHANGES_REQUESTED** [review]
1. There's still an `Abilities` folder directly under the project root which isn't following [project structure](https://docs.google.com/document/d/1G1FRt30GkujD9pizI5bsZ7yJgD05wlP7GjoBy02OS_c/)

If you move the files, GitHub Desktop should detect it as movement (or as a file deletion + a file addition, which has the exact same result). 

To the right in the commit files list, you'll see a plus/minus indicating if the file was added or removed. Commit both the deletion and the addition.

1. Commit the deletion of Packages also
Delete

**Review by FelixAtForsberg — COMMENTED** [review]
Why did you move the scene *away* from the correct folder?

**Review by FelixAtForsberg — APPROVED** [review]

**Pull request merged**
